module Admin
  class ContentsController < AdminBaseController
    before_action :set_interaction

    def index
      # :interaction set by AdminBaseController for index routes generated by fae after restful action
      if @interaction
        @items = Content.where(interaction_id: @interaction.id)
      else
        @items = Content.all
      end
    end

    private

    def build_assets
      @item.build_stimulus if @item.stimulus.blank?
    end

    def set_interaction
      @interaction = Interaction.find_by_id(params[:interaction])
    end

    def set_class_variables(class_name = nil)
      set_fae_variables
      @index_path = scoped_path                            # used in form_header and form_buttons partials
      @new_path = scoped_path('/new')                      # used in index_header partial
    end

    # add a parameter to the index path to scope the view to the parent
    def scoped_path(action = '')
      set_interaction
      scope = @interaction? "?interaction=#{@interaction.id}" : ''
      return '/' + params[:controller] + action + scope
    end

  end
end
