#!/bin/bash

mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/33
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/34
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/35
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/36
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/37
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/38
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/39
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/40
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/41
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/42
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/43
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/44
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/45
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/46
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/47
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/48
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/49
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/50
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/51
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/52
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/53
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/54
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/55
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/56
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/57
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/58
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/59
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/60
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/61
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/62
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/63
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/64
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/65
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/66
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/67
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/68
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/69
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/70
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/71
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/72
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/73
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/74
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/75
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/76
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/77
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/78
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/79
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/80
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/81
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/82
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/83
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/84
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/85
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/86
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/87
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/88
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/89
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/90
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/91
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/92
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/93
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/94
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/95
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/96
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/97
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/98
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/99
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/100
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/101
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/102
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/103
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/104
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/105
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/106
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/107
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/108
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/109
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/110
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/111
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/112
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/113
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/114
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/115
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/116
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/117
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/118
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/119
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/120
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/121
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/122
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/123
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/124
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/125
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/126
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/127
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/128
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/129
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/130
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/131
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/132
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/133
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/134
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/135
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/136
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/137
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/138
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/139
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/140
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/141
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/142
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/143
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/144
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/145
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/146
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/147
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/148
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/149
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/150
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/151
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/152
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/153
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/154
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/155
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/156
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/157
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/158
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/159
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/160
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/161
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/162
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/163
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/164
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/165
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/166
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/167
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/168
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/169
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/170
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/171
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/172
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/173
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/174
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/175
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/176
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/177
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/178
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/179
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/180
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/181
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/182
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/183
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/184
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/185
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/186
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/187
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/188
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/189
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/190
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/191
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/192
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/193
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/194
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/195
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/196
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/197
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/198
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/199
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/200
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/201
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/202
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/203
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/204
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/205
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/206
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/207
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/208
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/209
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/210
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/211
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/212
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/213
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/214
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/215
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/216
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/217
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/218
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/219
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/220
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/221
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/222
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/223
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/224
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/225
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/226
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/227
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/228
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/229
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/230
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/231
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/232
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/233
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/234
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/235
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/236
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/237
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/238
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/239
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/240
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/241
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/242
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/243
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/244
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/245
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/246
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/247
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/248
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/249
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/250
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/251
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/252
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/253
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/254
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/255
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/256
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/257
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/258
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/259
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/260
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/261
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/262
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/263
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/264
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/265
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/266
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/267
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/268
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/269
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/270
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/271
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/272
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/273
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/274
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/275
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/276
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/277
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/278
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/279
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/280
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/281
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/282
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/283
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/284
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/285
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/286
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/287
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/288
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/289
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/290
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/291
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/292
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/293
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/294
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/295
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/296
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/297
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/298
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/299
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/300
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/301
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/302
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/303
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/304
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/305
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/306
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/307
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/308
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/309
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/310
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/311
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/312
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/313
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/314
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/315
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/316
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/317
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/318
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/319
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/320
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/321
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/322
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/323
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/324
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/325
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/326
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/327
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/328
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/329
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/330
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/331
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/332
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/333
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/334
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/335
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/336
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/337
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/338
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/339
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/340
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/341
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/342
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/343
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/344
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/345
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/346
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/347
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/348
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/349
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/350
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/351
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/352
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/353
mkdir /Users/dbrandt/Projects/mm-api/public/system/uploads/fae/image/asset/354
